---
title: An R Forwards Presentation
subtitle: Subtitle
author: Your Name
date: last-modified
date-format: long
footer: <https://forwards.github.io>
format:
  forwardspres-revealjs: default
# To remove logo from title slide, comment out following line 
# in `"_extensions/forwards/forwardspres/_extension.yml"`
#   `data-background-image: forwards_hex_solid_border.svg`
---

## Introduction

This is a Quarto presentation format that is consistent with R Forward's brand.

<https://forwards.github.io>

It features the Forwards logo on the title slide.

. . .

:::{.callout-note}
To remove logo from title slide, **comment out** the following line
in `"_extensions/forwards/forwardspres/_extension.yml"`:

`data-background-image: forwards_hex_solid_border.svg`
:::

:::{.notes}
Speaker notes go here.
:::

# inverse class for section headings {.inverse}

## {.inverse .center-h .center .larger125}

inverse class is also useful for stressing *key points*. 

## Colours

There's a colour for inline code such as `x <- c(1, 3, 6)` and `{.inverse}`.

There's also a colour for short [links](https://github.com/forwards/forwardspres) and full ones like <https://quarto.org/docs/presentations/revealjs/>.

## Colours {.inverse}

There's a colour for inline code such as `x <- c(1, 3, 6)` and `{.inverse}`.

There's also a colour for short [links](https://github.com/forwards/forwardspres) and full ones like <https://quarto.org/docs/presentations/revealjs/>.

- The inline code and link colours change when the inverse class is applied.

## Code

The extension includes a custom syntax highlighting theme:

```{r}
#| echo: true
#| eval: false
library(dplyr)
library(palmerpenguins)

penguins %>%
  mutate(
    long_flipper = case_when(
      species == "Adelie" & flipper_length_mm > 195 ~ TRUE,
      species == "Chinstrap" & flipper_length_mm > 200 ~ TRUE,
      species == "Gentoo" & flipper_length_mm > 225 ~ TRUE,
      TRUE ~ FALSE
    )
  ) %>%
  mutate(
    body_mass_kg = body_mass_g / 1000,
    bill_length_cm = bill_length_mm / 10,
    bill_depth_cm = bill_depth_mm / 10
  )
```

## Callouts {.smaller80}

There are custom colours for callouts: 

:::{.callout-note}
A note
:::

:::{.callout-tip}
This is a good idea
:::

:::{.callout-important}
Something important
:::

:::{.callout-warning}
A warning
:::

:::{.callout-caution}
Be careful about doing this
:::


## Callouts {.smaller80 .inverse}

There are custom colours for callouts: 

:::{.callout-note}
A note
:::

:::{.callout-tip}
This is a good idea
:::

:::{.callout-important}
Something important
:::

:::{.callout-warning}
A warning
:::

:::{.callout-caution}
Be careful about doing this
:::

## Columns with backgrounds

::: {columns}
::: {.column .col-box-yellow width="32%"}
### Box 1

Use class `.col-box-{color}` to apply colour box styling, e.g. `.col-box-yellow`
:::

::: {.column .col-box-peach width="32%"}
### Box 2

Default height is 450px

This div has class `.col-box-peach`
:::

::: {.column .col-box-orange width="32%"}
### Box 3

This div has class `.col-box-orange`
:::
:::

## Columns with backgrounds: tall and short

::::: {columns}
:::: {.column .col-box-yellow-tall width="49%"}
Colour box styling can be applied to entire columns

This column has class `.col-box-yellow-tall`
::::

:::: {.column width="49%"}
:::{.col-box-peach-short}
Or to divs within columns to create stacks

This div has class `.col-box-peach-short`
:::

:::{.col-box-orange-short}
This div has class `.col-box-orange-short`
:::

::::

:::::

## Columns with backgrounds: tall and short {.inverse}

::::: {columns}
:::: {.column .col-box-plum-tall width="49%"}
Colour box styling can be applied to entire columns

This column has class `.col-box-plum-tall`
::::

:::: {.column width="49%"}
:::{.col-box-pink-short}
Or to divs within columns to create stacks

This div has class `.col-box-pink-short`
:::

:::{.col-box-purple-short}
This div has class `.col-box-purple-short`
:::

::::

:::::

# Non-Forwards-specific nice-to-haves {.inverse}

## Alignment

There are classes to help with text alignment:

:::{.center-h}
`{.center-h}` gives horizontally-centered text
:::

:::{.right}
`{.right}` gives right-aligned text
:::

:::{.callout-note}
For all revealjs Quarto presentations, applying `{.center}` to the slide title vertically centers the whole slide.
:::

## Sizing

There are classes to help size text by a given percentage:

[`{.smaller90}`]{.smaller90}, [`{.smaller80}`]{.smaller80}, [`{.smaller75}`]{.smaller75}
[`{.smaller70}`]{.smaller70}, [`{.smaller60}`]{.smaller60}, [`{.smaller50}`]{.smaller50}

[`{.larger125}`]{.larger125}, [`{.larger150}`]{.larger150}, [`{.larger175}`]{.larger175}, 
[`{.larger200}`]{.larger200}, [`{.larger250}`]{.larger250}

## More information

You can learn more about Quarto Revealjs presentations at <https://quarto.org/docs/presentations/revealjs/>

You can learn more about Quarto extensions at <https://quarto.org/docs/extensions/>

You can find these slides at <https://forwards.github.io/forwardspres/>
